### ISSUE TITLE
Raw data download failed

### ISSUE THREAD

**Issue by jincanke** [LieberInstitute/septum_lateral#6]
Hello, congratulations for your work, pulished in Transl Psychiatry(https://doi.org/10.1038/s41398-024-02758-6). I'm interested in the lateral septum and want to download your data for analysis, so I moved to this website(https://research.libd.org/globus/jhpce_septum_lateral/index.html), but I can't find your data, could you provide it for me?

**Comment by RyAMiller** [comment]
Hello thank you for your comment. 
A couple quick questions. Do you have a globus account? (it's free to sign up)
If you do, can you try and access the globus endpoint again?
I was having problems accessing it yesterday, but now it seems to be working fine for me, so I would like to double check to see if it is still an issue for you.

**Comment by jincanke** [comment]
Yes, I have a globus account and the connection failed before as well. Thanks for your help, now I can link and download.

**Comment by RyAMiller** [comment]
Temporary Globus issue that seems to have passed.
